### ISSUE TITLE
Redis vs infinispan  

### ISSUE THREAD

**Issue by seungeun90** [spring-React-blog/blog-server-se#3]
*레디스는"키-값" 구조의 비정형 데이터를 저장하고 관리하기 위한 
오픈 소스 기반의 비관계형 데이터베이스 관리 시스템(DBMS)이다.
기타 구조화된 스토리지 시스템 사이의 주요 차이점 중 하나는 레디스는 스트링뿐만 아니라 
자료구조의 추상적 자료형(Abstract Data Type)도 지원을 한다는 점이다.
[위키백과]https://ko.wikipedia.org/wiki/레디스

*Infinispan은 Red Hat이 개발 한 분산 캐시 및 키-값 NoSQL 데이터 저장소 소프트웨어이다.
동기화와 성능 이슈를 같이 해결한 것이 바로 ConcurrentMap 인터페이스이다. 
Infinispan이 제공하는 Cache 인터페이스 또한 ConcurrentMap 인터페이스를 확장한 형태이다.
[위키백과(영어)](https://en.wikipedia.org/wiki/Infinispan)

* 공통점 :  키-값 구조의 비관계형 데이터베이스 관리/저장 시스템 

* 둘의 가장 큰 차이점은 
redis 는  single-thread , master-slave 구조
infinispan 은  multi-thread , peer to peer 구조로 이루어져 있다는 것이다.

* 상황에 따라 목적에 맞는 솔루션을 선택하는 것이 중요하다.

* Redis는 성능과 영속성이 다른 기능보다 가장 중요한 애플리케이션에서 선택할 수 있다.

* infinispan 도 redis 보다 스케일링에 이점이 있다.
ifinispan 은 마스터 없는 노드 간 peer to peer  구조로 되어 있다.
이런 구조는 수직,수평적인 스케일링을 빠르게 할 수 있다는 장점이 있고,
만약 한 peer 가 실패할 경우 전체 시스템에 영향을 미치지 않는다. 이런 점은 가용성과 스케일링 장점을 가진다.
infinispan 은 멀티 코어 시스템에서 높은 작업량에 사용하기에 적합하다.

* infinispan 도 redis 와 같이 성능이 좋다.
멀티 스레드는 멀티코어 시스템에서 full performance 를 보장한다.
데이터 영속성 또한 가능하고, 서버가 죽으면 모든 데이터를 회복시킬수도 있다.

https://medium.com/geekculture/redis-vs-infinispan-vs-memcached-7f7cf3b26522
https://jsonobject.tistory.com/441
https://jsonobject.tistory.com/604

**Comment by ilgolf** [comment]
infinispan은 ConcurrentHashMap을 이용한 인터페이스 구현체에요. 결국 멀티스레드에서 계속 동기화를 통해 동시성 이슈를 막고 있어요 캐시는 단순 읽어오는 기능 뿐인데 성능 떨어지는 infinispan을 굳이 써야 할 이유가 없어요. 그리고 레디스에는 다양한 자료구조들이 존재해서 특정 규칙성 있는 데이터 저장에 용이합니다.

**Comment by ilgolf** [comment]
https://medium.com/geekculture/redis-vs-infinispan-vs-memcached-7f7cf3b26522

이건 제가 참고한 문서입니다.
